'\" t
.\"     Title: LibNoWebsocket
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 08/09/2018
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "LIBNOWEBSOCKET" "3" "08/09/2018" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
nowsread, nowswrite, nowsclose \- read, write, close a regular stream socket when peer is a websocket\&.
.SH "PROLOG"
.sp
This manual page will never be part of the POSIX Programmer\(cqs Manual\&.
.sp
nowsread, nowswrite and nowsclose are designed to be similar to posix read, write and close\&. Their purpose is to provide native sockets to HTML5 web browsers\&. This is not yet allowed by standards, but the other way around is not forbidden\&. These functions mimic posix\(cqs read, write and close and transparently emulate the websocket protocol\&.
.sp
These functions allow their users to communicate with HTML5\-enabled web browsers using legacy knowledge and habits gained through years of experience on network programming with TCP stream sockets and POSIX API as a reference\&.
.SH "SYNOPSYS"
.sp
#include <nows\&.h>
.sp
ssize_t nowsread (int \fBsock\fR, void* \fBdata\fR, size_t \fBlen\fR);
.sp
ssize_t nowswrite (int \fBsock\fR, const void* \fBdata\fR, size_t \fBlen\fR);
.sp
int nowsclose (int \fBsock\fR);
.sp
int nows_simulate_client (int \fBsock\fR);
.SH "DESCRIPTION"
.sp
nowsread(3) is very similar to read(3POSIX) in its arguments, behavior, return value, in blocking or non blocking mode, when \fBsock\fR is a STREAMS socket in \fIbyte\-stream\fR mode (\fImessage\-nondiscard\fR and \fImessage\-discard\fR modes are yet unconsidered)\&. Same goes to nowswrite(3) regarding write(3POSIX)\&. The websocket protocol includes a handshake process which sadly breaks symmetry between peers\&. As generally HTML5 browsers act as websocket clients, nowsread(3) and nowswrite(3) act by default as websocket server (even if the socket \fBsock\fR is a SOCK_STREAM client)\&. A call to nows_simulate_client(3) prior to nowsread(3) and nowswrite(3) will switch this behavior\&.
.sp
Nothing beeing perfect, here is a list of specific differences or relevant notices:
.PP
\fB\- blocking mode\fR
.RS 4
read(3POSIX) blocks the caller until exactly
\fBlen\fR
bytes are received\&. Similarly nowsread(3) blocks the caller until at least one byte is received, but due to the nature of the websocket protocol, this does not guarantee that exactly
\fBlen\fR
bytes are received\&. The returned value indicates the amount of received bytes in the
\fBdata\fR
buffer\&. nowswrite(3) has however the same behavior as write(3POSIX)\&.
.RE
.PP
\fB\- non\-blocking mode\fR
.RS 4
Any value (greater than 0) given to
\fBlen\fR
will follow read/write(3POSIX) behavior\&.
.RE
.PP
\fB\- websocket specifics or restrictions\fR
.RS 4
Underlying ping\-pong facility is not implemented yet\&. Only text buffers are sent or received\&. This is subject for improvements\&.
.RE
.sp
nowsclose(3) is similar to close(3POSIX)\&.
.sp
nows_simulate_client(3) sets this side of the stream to act as a websocket client\&.
.SH "RETURN VALUE"
.sp
Please refer to read(3POSIX), write(3POSIX)\&. To summarize, 0 always indicates EOF, \-1 an error and in that case \fBerrno\fR is set\&. \fBerrno\fR can be set to EAGAIN even when in blocking mode\&. However in blocking mode EAGAIN is never continuously returned and cannot induce an active loop\&. Otherwise the returned value indicates the number of bytes sent or received\&.
.sp
now_simulate_client(3) returns 0 on success, \-1 on error and in that case \fBerrno\fR is set\&.
.SH "ERRORS"
.sp
They are the same as with read(3POSIX), write(3POSIX) and close(3POSIX)\&. Additionnaly,
.PP
\fBENOMEM\fR
.RS 4
can be returned in case of memory shortage\&.
.RE
.PP
\fBEAGAIN\fR
.RS 4
can be returned by nowsread(3) or nowswrite(3) in blocking mode (however never continuously thus not inducing an active loop)\&. This is subject for improvements\&.
.RE
.SH "LICENSE"
.sp
GPLv2 (due to sha1 embedded library \- subject for changes)
.SH "AUTHOR"
.sp
CNRS
.sp
https://redmine\&.laas\&.fr/projects/libnowebsocket
